
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: abc+!@#123
    url: jdbc:postgresql://localhost:5432/daily-book
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    showsql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8888
#mybatis:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#mybatis:
#  mapper-locations: classpath:/
